// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: SearchMax.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace SearchMax {
  public static partial class SearchMaxService
  {
    static readonly string __ServiceName = "SearchMax.SearchMaxService";

    static readonly grpc::Marshaller<global::SearchMax.Request> __Marshaller_SearchMax_Request = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::SearchMax.Request.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::SearchMax.Response> __Marshaller_SearchMax_Response = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::SearchMax.Response.Parser.ParseFrom);

    static readonly grpc::Method<global::SearchMax.Request, global::SearchMax.Response> __Method_SearchMaxNumber = new grpc::Method<global::SearchMax.Request, global::SearchMax.Response>(
        grpc::MethodType.DuplexStreaming,
        __ServiceName,
        "SearchMaxNumber",
        __Marshaller_SearchMax_Request,
        __Marshaller_SearchMax_Response);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::SearchMax.SearchMaxReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of SearchMaxService</summary>
    [grpc::BindServiceMethod(typeof(SearchMaxService), "BindService")]
    public abstract partial class SearchMaxServiceBase
    {
      public virtual global::System.Threading.Tasks.Task SearchMaxNumber(grpc::IAsyncStreamReader<global::SearchMax.Request> requestStream, grpc::IServerStreamWriter<global::SearchMax.Response> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for SearchMaxService</summary>
    public partial class SearchMaxServiceClient : grpc::ClientBase<SearchMaxServiceClient>
    {
      /// <summary>Creates a new client for SearchMaxService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public SearchMaxServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for SearchMaxService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public SearchMaxServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected SearchMaxServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected SearchMaxServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual grpc::AsyncDuplexStreamingCall<global::SearchMax.Request, global::SearchMax.Response> SearchMaxNumber(grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SearchMaxNumber(new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncDuplexStreamingCall<global::SearchMax.Request, global::SearchMax.Response> SearchMaxNumber(grpc::CallOptions options)
      {
        return CallInvoker.AsyncDuplexStreamingCall(__Method_SearchMaxNumber, null, options);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override SearchMaxServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new SearchMaxServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(SearchMaxServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_SearchMaxNumber, serviceImpl.SearchMaxNumber).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, SearchMaxServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_SearchMaxNumber, serviceImpl == null ? null : new grpc::DuplexStreamingServerMethod<global::SearchMax.Request, global::SearchMax.Response>(serviceImpl.SearchMaxNumber));
    }

  }
}
#endregion
