// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: primenumberdecomposition.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Primenumberdecomposition {
  public static partial class NumberService
  {
    static readonly string __ServiceName = "primenumberdecomposition.NumberService";

    static readonly grpc::Marshaller<global::Primenumberdecomposition.Request> __Marshaller_primenumberdecomposition_Request = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Primenumberdecomposition.Request.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Primenumberdecomposition.Response> __Marshaller_primenumberdecomposition_Response = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Primenumberdecomposition.Response.Parser.ParseFrom);

    static readonly grpc::Method<global::Primenumberdecomposition.Request, global::Primenumberdecomposition.Response> __Method_GetPrimeNumberDecomposition = new grpc::Method<global::Primenumberdecomposition.Request, global::Primenumberdecomposition.Response>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "GetPrimeNumberDecomposition",
        __Marshaller_primenumberdecomposition_Request,
        __Marshaller_primenumberdecomposition_Response);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Primenumberdecomposition.PrimenumberdecompositionReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of NumberService</summary>
    [grpc::BindServiceMethod(typeof(NumberService), "BindService")]
    public abstract partial class NumberServiceBase
    {
      public virtual global::System.Threading.Tasks.Task GetPrimeNumberDecomposition(global::Primenumberdecomposition.Request request, grpc::IServerStreamWriter<global::Primenumberdecomposition.Response> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for NumberService</summary>
    public partial class NumberServiceClient : grpc::ClientBase<NumberServiceClient>
    {
      /// <summary>Creates a new client for NumberService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public NumberServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for NumberService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public NumberServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected NumberServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected NumberServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual grpc::AsyncServerStreamingCall<global::Primenumberdecomposition.Response> GetPrimeNumberDecomposition(global::Primenumberdecomposition.Request request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetPrimeNumberDecomposition(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncServerStreamingCall<global::Primenumberdecomposition.Response> GetPrimeNumberDecomposition(global::Primenumberdecomposition.Request request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_GetPrimeNumberDecomposition, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override NumberServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new NumberServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(NumberServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_GetPrimeNumberDecomposition, serviceImpl.GetPrimeNumberDecomposition).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, NumberServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_GetPrimeNumberDecomposition, serviceImpl == null ? null : new grpc::ServerStreamingServerMethod<global::Primenumberdecomposition.Request, global::Primenumberdecomposition.Response>(serviceImpl.GetPrimeNumberDecomposition));
    }

  }
}
#endregion
